export default {
  CREATE_CONTACT: 'CREATE_CONTACT',
  GET_ALL_CONTACTS: 'GET_ALL_CONTACTS',
  LIKE_FAVORITE_CONTACT: 'LIKE_FAVORITE_CONTACT',
  GET_FAVORITE_CONTACT: 'GET_FAVORITE_CONTACT',
  EDIT_CONTACT: 'EDIT_CONTACT',
  LIKE_ALL_CONTACT: 'LIKE_ALL_CONTACT',
};
